Style/PredicateName:
  NameWhitelist: is_are

AllCops:
  Exclude:
    - db/schema.rb
  TargetRubyVersion: 2.3

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

LambdaCall:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/AndOr:
  EnforcedStyle: conditionals

Style/UnneededInterpolation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Style/AsciiComments:
  Enabled: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Style/StructInheritance:
  Enabled: false

Style/OptionalArguments:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineAssignmentLayout:
  EnforcedStyle: new_line

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Lint/AmbiguousOperator:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Lint/DefEndAlignment:
  AutoCorrect: true

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Documentation:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

LineLength:
  Enabled: false
